<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BannerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('banners')->insert([
            [
                'title' => null,
                'description' => null,
                'button_text' => null,
                'button_url' => null,
                'theme' => 'light',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1787126207/banner_14_goc_nho_l6apf6.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => null,
                'description' => null,
                'button_text' => null,
                'button_url' => null,
                'theme' => 'light',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1787126207/banner_13_check_in_f4rlfo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => null,
                'description' => null,
                'button_text' => null,
                'button_url' => null,
                'theme' => 'light',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1787126207/banner_12_tan_huong_vdfq3v.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => null,
                'description' => null,
                'button_text' => null,
                'button_url' => null,
                'theme' => 'light',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1787121645/banner_11_tra_vai_w4ltd1.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => null,
                'description' => null,
                'button_text' => null,
                'button_url' => null,
                'theme' => 'light',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1787121645/banner_10_tra_dau_b6riz3.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => null,
                'description' => null,
                'button_text' => null,
                'button_url' => null,
                'theme' => 'light',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1787121645/banner_9_tra_dao_kwvsjf.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => null,
                'description' => null,
                'button_text' => null,
                'button_url' => null,
                'theme' => 'light',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1787121645/banner_8_tra_chanh_day_tzsadw.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => null,
                'description' => null,
                'button_text' => null,
                'button_url' => null,
                'theme' => 'light',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1780983258/banner_1_khai_truong_jkncuo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => null,
                'description' => null,
                'button_text' => null,
                'button_url' => null,
                'theme' => 'light',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1780983258/banner_5_mon_moi_xq89lc.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => null,
                'description' => null,
                'button_text' => null,
                'button_url' => null,
                'theme' => 'light',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1780983259/banner_4_mon_noi_bat_u3imia.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nắng ấm áp, Cà phê đậm đà',
                'description' => "Bắt đầu ngày mới đầy năng lượng với hương vị cà phê mộc mạc và không gian ngập tràn ánh nắng tại Nắng Coffee.",
                'button_text' => "Xem menu",
                'button_url' => "http://localhost:8000/thuc-don",
                'theme' => 'dark',
                'text_align' => 'center',
                'position' => 'center',
                'image_url' => 'https://res.cloudinary.com/dltgjdf9t/image/upload/v1783495774/background_nangcoffee_gdibni.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
